log_dir=/home/etienne/d3cs-prototype/benchmark_results/multihop/run-1791216455/hops-1/lepton
lepton_host=localhost
jitter=0
time_margin=0
nodes_deferred=0
accel=1
simul_area=car:-20,-20,300,40
edge_default_status=DISCONNECTED
node_default_status=NONE
range=60
lepton_console_port=5100
in_dgs=/home/etienne/d3cs-prototype/benchmark_results/multihop/run-1791216455/hops-1/chain.dgs
in_hist=/home/etienne/d3cs-prototype/benchmark_results/multihop/run-1791216455/hops-1/nodes.hist
make_edges=false
nodes=0
period=1.0
duration=-1
out_dgs=/home/etienne/d3cs-prototype/benchmark_results/multihop/run-1791216455/hops-1/lepton/lepton.dgs
nodes_profiles=/home/etienne/d3cs-prototype/benchmark_results/multihop/run-1791216455/hops-1/node_profiles.txt
node_labels=/home/etienne/d3cs-prototype/benchmark_results/multihop/run-1791216455/hops-1/node_labels.txt
